import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { fetchRepos } from '@webservices';

export const initialState = {};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchReposAsync = createAsyncThunk('folio/fetchRepos', async () => {
  return await fetchRepos();
});

export const folioSlice = createSlice({
  name: 'folio',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchReposAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchReposAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.repos = action.payload;
      });
  }
});

export const {} = folioSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.folio.value)`
export const selectfolio = (state) => state.folio;

export const folioReducer = folioSlice.reducer;
